apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-dep
  labels:
    app: node-server-dep
spec:
  replicas: 1
  template:
    metadata:
      name: node-server-dep
      labels:
        app: node-server-dep
    spec:
      containers:
        - name: node-server-dep
          image: simple-node-server:1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: node-server-dep
---
apiVersion: v1
kind: Service
metadata:
  name: node-ser-svc
  labels:
    app: node-ser-svc
spec:
  selector:
    app: node-server-dep
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-ser-ingress
spec:
  rules:
    - host: nodeserver.local
      http:
        paths:
          - path: /
            backend:
              serviceName: node-ser-svc
              servicePort: 8080

